### PR TITLE
chore: use webcrypto over tweetnacl

### PR DESCRIPTION
**Pull request by garbados**
This PR swaps out TweetNaCl for [webcrypto](https://nodejs.org/api/webcrypto.html), a browser standard and experimental NodeJS API.

Unfortunately the result is... very slow. And it doesn't appear to work in the browser:

```
Uncaught TypeError: (intermediate value).webcrypto is undefined
    <anonymous> http://localhost:5000/bundle.js:1
    <anonymous> http://localhost:5000/bundle.js:1
```

As for the performance...

```
$ npm test

> garbados-crypt@1.0.0-alpha test
> standard && dependency-check --unused --no-dev . && mocha



  crypt
    ✓ should do the crypto dance
    ✓ should fail to decrypt ok
    ✓ should do the crypto dance 1000 times (10478ms)


  3 passing (11s)
```

Each encryption and decryption operation takes about 5ms. This is astonishingly slow relative to TweetNaCl, making me reticent to accept it as an alternative.

Comments welcome.

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
first issue: `require('crypto').webcrypto` in browserify doesn't work so you probably need to have a file that switches between node and the brower that either has `module.exports = require('crypto').webcrypto` or `module.exports = globalThis.crypto`

**Comment by calvinmetcalf** [comment]
ok as for slowness two things:
1. the nacl version wasn't using a key strengthening algorithm  at all (which is intentionally slow) so that could be slowing things down.  It looks like what you are doing is saving the password as itself and then using the key derivation algorithm on each encryption to generate a new key, what you probably want to do is have `getKeyFromPassword` run the key derivation algorithm just once instead of doing it on every encryption. 
2. the webcrypto one is async while the nacl is not, I don't know how you are doing you're tests but the latency inherent to async operations can often make async ones look slower then they'd be in an app.  Plus the webcrypto ones are going to be totally non blocking while the nacl ones could block a bit especially if doing a lot in a row so even it turns out to actually be slower it's a tradeoff that may be acceptable.

**Comment by calvinmetcalf** [comment]
ok on 2nd thought yes you do need to probably do need to derive the password on each message since it's for one off communications that have to include the salt with them, so the real speed difference is just that with nacl you could brute force the password to a message very easily while with one you couldn't because it takes longer

**Comment by garbados** [comment]
@calvinmetcalf Hey, thanks for this feedback! It really helps. That confirmation that I'm doing things right-ish here is good motive to keep at it.

**Comment by garbados** [comment]
I've just added some rudimentary cross-platform support along with [mochify](https://github.com/mantoni/mochify.js) for testing. Everything seems to be working properly now.

Basically, we use webcrypto if we can find it, or we fallback to using NodeJS crypto. The differences get disambiguated during import into an intermediate object `crypto` that exposes `.getKeyFromPassword`, `.encrypt`, and `.decrypt` methods, which Crypt then uses.

**Comment by garbados** [comment]
The major drawback here is that bundling NodeJS crypto adds about 500KB to a browserify bundle. For comparison, using tweetnacl, the bundle size if 50KB. That's considerable!! I sure hope we can shrink it down.

@calvinmetcalf Any ideas here?

**Comment by garbados** [comment]
OK, so I was able to get as low as 375KB:

```
$ npm run build
$ stat bundle.min.js 
  File: bundle.min.js
  Size: 375035
```

Hm.

**Comment by garbados** [comment]
Looks like others have [taken issue](https://github.com/braintree/braintree-web/issues/386) with the size of crypto-browserify as well. It looks like it's getting a nice [refresh](https://github.com/crypto-browserify/crypto-browserify/pull/200) but I don't know when to expect bundling optimizations from it.

For now I'm content to leave this PR open for further discussion while the main branch retains the use of tweetnacl. Given the status of its audit, I am not inclined to consider it a vulnerability.

**Comment by garbados** [comment]
Had a thought and my hand slipped and now the bundle is only 26kb. Essentially you tell Browserify to explicitly not bundle `require('crypto')` calls, which chops off a little more than 350k in shims. That's smaller than requiring tweetnacl.

Downstream users will still face this bundling problem until crypto-browserify sees the relevant improvements.

**Comment by garbados** [comment]
Thanks Calvin, that's great. I'll see what I can do.

**Comment by calvinmetcalf** [comment]
there may be a node only polyfill that you could prevent from being bundled, the real question is how bad is browser support and do you want to include a polyfill

**Comment by garbados** [comment]
I was able to add support for node 12 and 14 and the bundle only grew to 4.5kb, which is fine. The trick was not compiling `Buffer`, which costs about 20kb. Unfortunately this, inexplicably, broke the build.

**Comment by garbados** [comment]
Build fixed. I think my only remaining worry is that only rather recent browsers are supported by this model -- I had to update my local firefox to get it to work outside of the testing environment -- but I'm otherwise ready to hit merge.

**Comment by garbados** [comment]
OK. I've added an addendum about not excluding crypto from bundling in order to support older browsers. That's enough compatibility for me!

**Comment by garbados** [comment]
After some time and reflection, I don't believe this is the best way forward right now. Rather than rely on a complex web of unaudited dependencies to facilitate native-ish cryptography, I'm going to stick with the thing that has been audited.

**Pull request closed without merging**
